// Write rendered frames + gcsv + encode.bat directly to a user-picked folder
// via the File System Access API (Chromium-only).
window.APP = window.APP || {};
APP.exports = APP.exports || {};
(function () {
  function assertFSA() {
    if (typeof window.showDirectoryPicker !== "function") {
      throw new Error("此瀏覽器不支援 File System Access API,請用 Chrome 或 Edge");
    }
  }

  APP.exports.pickDirectory = function pickDirectory() {
    assertFSA();
    return window.showDirectoryPicker({ mode: "readwrite" });
  };

  APP.exports.pickSaveFile = function pickSaveFile(suggestedName, description, ext) {
    if (typeof window.showSaveFilePicker !== "function") {
      throw new Error("此瀏覽器不支援 File System Access API,請用 Chrome 或 Edge");
    }
    const accept = {};
    accept["text/plain"] = [ext];
    return window.showSaveFilePicker({
      suggestedName,
      types: [{ description, accept }],
    });
  };

  APP.exports.writeFileHandle = async function writeFileHandle(handle, data) {
    const w = await handle.createWritable();
    await w.write(data);
    await w.close();
  };

  APP.exports.writeFramesAndScripts = async function writeFramesAndScripts(opts) {
    const { dirHandle, frameCount, fps, getFrameBlob, gcsvText, progress } = opts;

    for (let i = 0; i < frameCount; i++) {
      const name = "f" + String(i).padStart(6, "0") + ".jpg";
      const fh = await dirHandle.getFileHandle(name, { create: true });
      const blob = await getFrameBlob(i);
      await APP.exports.writeFileHandle(fh, blob);
      if (i % 5 === 0 || i === frameCount - 1) {
        progress && progress("寫入影格 " + (i + 1) + "/" + frameCount);
      }
    }

    const gcsvHandle = await dirHandle.getFileHandle("output.gcsv", { create: true });
    await APP.exports.writeFileHandle(gcsvHandle, new Blob([gcsvText], { type: "text/csv" }));

    // encode.bat — ASCII only. Windows CMD mangles UTF-8 text by default and
    // the `del` branch never runs if the preceding echo blows up on encoding.
    // Literal percent must be doubled inside a batch file.
    const bat = [
      "@echo off",
      "REM Auto-generated by EIS test video generator",
      "REM fps = " + fps,
      "setlocal",
      "cd /d \"%~dp0\"",
      "",
      "where ffmpeg >nul 2>nul",
      "if errorlevel 1 (",
      "  echo [ERROR] ffmpeg not found in PATH",
      "  pause",
      "  exit /b 1",
      ")",
      "",
      "ffmpeg -y -framerate " + fps + " -i f%%06d.jpg -c:v libx264 -pix_fmt yuv420p -crf 18 output.mp4",
      "if errorlevel 1 (",
      "  echo [ERROR] ffmpeg encode failed, JPG frames kept",
      "  pause",
      "  exit /b 1",
      ")",
      "",
      "echo Deleting JPG frames ...",
      "del /q f*.jpg",
      "echo Done: output.mp4",
      "pause",
      "",
    ].join("\r\n");
    const batHandle = await dirHandle.getFileHandle("encode.bat", { create: true });
    await APP.exports.writeFileHandle(batHandle, new Blob([bat], { type: "text/plain" }));

    progress && progress("完成");
  };
})();
